-- MySQL Script generated by MySQL Workbench
-- Wed Aug 19 20:59:50 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema kampin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kampin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kampin` DEFAULT CHARACTER SET utf8 ;
USE `kampin` ;

-- -----------------------------------------------------
-- Table `kampin`.`cancha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kampin`.`cancha` (
  `IDcancha` CHAR(3) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `N_Cancha` INT NOT NULL,
  PRIMARY KEY (`IDcancha`, `N_Cancha`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kampin`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kampin`.`cliente` (
  `IDcliente` CHAR(5) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `NumeroCelular` CHAR(9) NOT NULL,
  `DNI` CHAR(8) NULL,
  PRIMARY KEY (`IDcliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kampin`.`tiempo_reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kampin`.`tiempo_reserva` (
  `HoraInicio` TIME NOT NULL,
  `HoraFinal` TIME NOT NULL,
  `Fecha` DATETIME NOT NULL,
  `Costo` FLOAT NOT NULL,
  `Total_hora` FLOAT NOT NULL,
  `IDcancha` CHAR(3) NOT NULL,
  `N_Cancha` INT NOT NULL,
  PRIMARY KEY (`Fecha`),
  INDEX `fk_tiempo_reserva_cancha_idx` (`IDcancha` ASC, `N_Cancha` ASC) VISIBLE,
  CONSTRAINT `fk_tiempo_reserva_cancha`
    FOREIGN KEY (`IDcancha` , `N_Cancha`)
    REFERENCES `kampin`.`cancha` (`IDcancha` , `N_Cancha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kampin`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kampin`.`usuario` (
  `IDusuarios` CHAR(5) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Numcelular` CHAR(9) NOT NULL,
  `Foto` BLOB NULL,
  PRIMARY KEY (`IDusuarios`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kampin`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kampin`.`reserva` (
  `idreserva` CHAR(5) NOT NULL,
  `Adelanto` FLOAT NULL DEFAULT NULL,
  `Total` FLOAT NULL DEFAULT NULL,
  `Cancelado` CHAR(2) NULL DEFAULT NULL,
  `IDcliente` CHAR(5) NOT NULL,
  `IDusuarios` CHAR(5) NOT NULL,
  `Fecha` DATETIME NOT NULL,
  `Falta` FLOAT NULL,
  PRIMARY KEY (`idreserva`),
  INDEX `fk_RESERVA_CLIENTE_idx` (`IDcliente` ASC) VISIBLE,
  INDEX `fk_RESERVA_USUARIO_idx` (`IDusuarios` ASC) VISIBLE,
  INDEX `fk_RESERVA_CANCHA_idx` (`Fecha` ASC) VISIBLE,
  CONSTRAINT `fk_RESERVA_CANCHA`
    FOREIGN KEY (`Fecha`)
    REFERENCES `kampin`.`tiempo_reserva` (`Fecha`),
  CONSTRAINT `fk_RESERVA_CLIENTE`
    FOREIGN KEY (`IDcliente`)
    REFERENCES `kampin`.`cliente` (`IDcliente`),
  CONSTRAINT `fk_RESERVA_USUARIO`
    FOREIGN KEY (`IDusuarios`)
    REFERENCES `kampin`.`usuario` (`IDusuarios`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
